language: ruby
rvm:
- 2.2
sudo: false
env:
  secure: qrouMQOs3wCY1hIct8aHKKv+k+BmAqRoda3IdsGj6iFbVdqqENh8PxE1iQhFo54h068N1iuUVijIoeKQ8KBbAB46p529sYhhDRvq5KP8sR1xxT5fl/JdfM04xdK5mo4Cw1v1WVh45dc45nLofEaIQBiXHxIxKJ8m5unvbaIlURyBXqUEYcNZnZnUPcEsF4oBSz3Is6/BgD1wifL8wmnoXc1sAaxg1SenguFk/lr1R8mx3wEmJrRTJ2L/80ltXeMfsqubNBgJK2NQyo0FcTQ4QEfLnoPMLfBcw7q8BmwkkvlzZMZyFJr9gLLZDiCMvuM5na5Ck5daKSkQLEY4+2ZWJ/YkGZUwK222RoLKkZPGKZ/6QOY8HZuE3grLIVL5wlo/2Fgjq+3iHYvKh/bzjZ4xPdhHPRHUGxzhJg8+x3gL1MOxzYgt/cyoh9u6Nh/JE8cGbIaUJNPV9nbT844uLjVl9NoOH0Ot1Ca6wK/fQIIQR5fGINBaBp1leeFDUYFUGHNw48yrAu+kxqnIsrKhtGrWImiylE3/ZCR2uQpi/d0NZia6EzNmcPjObTS5Gcif2BMpdGm5NDVAgbSHhdF3Gt6Gs6Aoxni/IJy6//fg7d7uP3mhxaCVx3WBUIJAB9ZBL5EVvLCf79ypDERbOxdmSyj01Y6wNfybExtpBF1SEfNAN20=
before_install:
- gem install dropbox-deployment mdl
script:
- sh check_readme.sh
after_success:
- ruby converter.rb
- dropbox-deployment
notifications:
  slack:
    secure: ZOAFVoebeOOQHvJXpQgdQ3ejRYL5/ox6RHQioMsAyqyuR+exmAWbUEV0twGFNyau7y4GWk5hZ0oEUV8FFf4+Sn7Kk8A7QlYbaNpnX6nckZlaSi5L+oaN6Q/GjcUbE+F0Rn4y2tPvPqP0IKsC3idx9ZyiWbtQawxgTirW+WP+wpXTj/KcjtZi0sZFSIv2E17Yn57+YioFhHuhtHbS8mFd+7WhCzNwIy+MlXGTR/uNFR0QnAtguRVrQ210/WV5OgowlOCjqPf62hhJACfx1DlLnn1sjJnYJ9EdknybOkdbWU57gGwZEGwtUyP1JVQ/QEqT4XwvarsVmTKVHjbEd9jW0zlZWmvhCAEihBDWnFGIxLwCxL7wHk35hagMaADVQVh6YmGH/dJS4bg6VWIEI0N21MgqOpP4fV5Z8ph6/Vu4+fYfqNhuPu0FAmhU1CN5uIjo2ETtKUHp2B79yeJ5MZiMeudhgIkH5VTxOQw0iN0b7Kxv1BkkhKeNmX/36gQCvG6cX8VAYaYxNuU1nPO8DcDNIwtF1MzkCVzXMSMS9NtcirWyhevofJQbw0cEXuMMQ9DyPyBo5qiS3AMTk2dNMBW+HVGb1gz8zga+RiswnuEGJDtU1nThlNiDaZGJWecgxXkUyQpitfpQkj2KwXB4wiFg7JKytrxAq4fiHw62J6e+rqA=
